version: '3.8'

services:

  wordpress:
    depends_on: 
      - mysql
    image: wordpress
    restart: always
    networks:
      - wordperss-network
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./data/wordpress:/var/www/html


  mysql:
    image: mysql:8.0
    restart: always
    networks:
      - wordperss-network
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./conf/mysql/conf.d:/etc/mysql/conf.d

  phpmyadmin:
    depends_on: 
      - mysql
    image: phpmyadmin
    restart: always
    networks:
      - wordperss-network
    ports:
      - 8081:80
    environment:
        PMA_HOST : mysql
        MYSQL_ROOT_PASSWORD : password 

  nginx:
    depends_on: 
      - wordpress
    image: nginx
    networks:
      - wordperss-network
    volumes:
    - ./data/nginx:/etc/nginx/templates
    - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
    - "80:80"
  
  network-validation-vm:
    image: nicolaka/netshoot
    networks:
      - wordperss-network   
    command: tail -f /dev/null 

networks:
  wordperss-network:


